# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://blaise.github.io/nb_solve/"

git_url = "https://github.com/blaise/nb_solve/tree/master/"

def custom_doc_links(name): return None
